### PR TITLE
Paginate admin lists

### PR DESCRIPTION
**Pull request by ccassell**
Ensure that users, groups, integrations admin methods can be paginated manually or internally.

### CODE REVIEW

**Comment by ccassell** [comment]
> Clients shouldn't be worrying about setting `$limit` or `$offset` when calling these APIs. The API was designed to automatically handle it for them, e.g. `$paging` defaults to `true`, which will call `jsonPagingApiCall`, which handles paging automagically.

Pagination will be required soon. If the class is instantiated with `$paging = false`, the caller will only get the first page of results.

The python client exposes `limit` and `offset` in the signatures of methods that return lists, so part of the thinking is that the PHP client should be consistent with that. It also allows the consumer to manually page if desired.

If we don't want to expose limit and offset, then perhaps the fix is to ignore the `$paging` flag.

**Comment by ccassell** [comment]
Updated to remove `$limit` and `$offset`, and always paginate if the single item isn't requested.

**Comment by mschwager** [comment]
> Pagination will be required soon. If the class is instantiated with `$paging = false`, the caller will only get the first page of results.
> 
> The python client exposes `limit` and `offset` in the signatures of methods that return lists, so part of the thinking is that the PHP client should be consistent with that. It also allows the consumer to manually page if desired.

Do/will consumers want to manually page the results? In my opinion, providing a "batteries included" solution that solves for 99.9% of use cases with a dead simple API will make consumers lives easier. And for the 0.1% who need modified behavior, they can always subclass `Client` and overwrite the `jsonPagingApiCall` behavior. That may sound like a lot of work, but introducing friction at certain points will help keep consumers on the paved road :)

> If we don't want to expose limit and offset, then perhaps the fix is to ignore the `$paging` flag.

I like it! Although I have one suggestion: if we're ready for it from the Duo cloud API perspective, we should unconditionally call `jsonPagingApiCall` instead of `jsonApiCall`. The `$paging` flag was just a stop-gap solution until we were definitely ready to _only_ make paging calls (and could thus remove the flag).

This is one reason I like keeping the interface the same between paging calls and non-paging calls. We can modify the implementation how we see fit, and consumers won't have to change a thing!

**Comment by ccassell** [comment]
> I like it! Although I have one suggestion: if we're ready for it from the Duo cloud API perspective, we should unconditionally call `jsonPagingApiCall` instead of `jsonApiCall`. The `$paging` flag was just a stop-gap solution until we were definitely ready to _only_ make paging calls (and could thus remove the flag).

I branched the logic to use the `jsonApiCall` when fetching a single record, and `jsonPagingApiCall` when fetching a list. Would you prefer it to call `jsonPagingApiCall` in every case?

**Pull request merged**
