### PR TITLE
Fix issue with auth_status call

### PR DESCRIPTION
**Pull request by zmilan**
[Based on documentation for checking auth status](https://duo.com/docs/authapi#/auth_status) API expect **GET** request, not **POST** one.

### CODE REVIEW

**Comment by mschwager** [comment]
Good catch, thank you!

**Comment by zmilan** [comment]
You are welcome. I was wondering why I'm getting 'method not allowed' and then research start, so it was easy to catch, it is small function :)

**Comment by mschwager** [comment]
Just a heads up @zmilan, we tagged a version with the fix you added: https://packagist.org/packages/duosecurity/duo_api_php#1.0.1

**Comment by zmilan** [comment]
Great @mschwager thanks :+1:

**Pull request merged**
