### PR TITLE
Add create bypass code functionality

### PR DESCRIPTION
**Pull request by jlmaners**
Extended the Admin client and provided tests to consume the Create Bypass Codes endpoint from the API.

### CODE REVIEW

**Comment by mschwager** [comment]
Hey @jlmaners, thanks for reaching out to us!

This library's Admin API is purposefully not fully implemented: https://github.com/duosecurity/duo_api_php/blob/master/src/Admin.php#L22

The Admin API functionality is constantly changing, and keeping up with this change across all our language implementations would be a huge time sync. We've thus decided to implement a _few_ functions to serve as a reference and ask that consumers of this library add the functions they need.

To do this I'd recommend creating a new class that extends the `Admin` class within your code base. From here I'd recommend implementing the functionality you need on this subclass.

Let me know if you have any questions!

**Comment by jlmaners** [comment]
@mschwager thanks for that insight. I hadn't read that line as a "we don't ever plan to implement anymore" and more of a "we probably won't" and thus why I thought you might entertain the pull request. I've already been extending this functionality in some other situations, so not a problem there.

Feel free to close if no desire to merge.

**Comment by mschwager** [comment]
Thanks for understanding @jlmaners! I appreciate you reaching out to us :)

**Comment by mschwager** [comment]
Hmm, it seems that I can't close this because it's a read-only mirror repository.

**Pull request closed without merging**
