### PR TITLE
Support PHP 8.2

### PR DESCRIPTION
**Pull request by maxnz**
Add class property declarations to remove warnings about the [deprecation of dynamic properties](https://www.php.net/releases/8.2/en.php#deprecate_dynamic_properties).

Some dependency conflicts exist now so those will have to be fixed.

### CODE REVIEW

**Comment by maxnz** [comment]
@AaronAtDuo any updates on this?

**Comment by AaronAtDuo** [comment]
@maxnz This looks great and I look forward to merging it ASAP.  However we have some maintenance going on for this repo at the moment and can't merge PRs currently.  Ideally that will be resolved within a few days; sorry for the wait.

**Comment by maxnz** [comment]
Awesome, thank you!

**Comment by AaronAtDuo** [comment]
@maxnz For some reason (probably related to the maintentance I mentioned) the CI job did not trigger on this PR...

I _think_ if you push another commit (maybe something innocuous like a comment or something) it should pick up this time.  Worst case scenario, re-do the PR but hopefully it won't come to that.

**Pull request closed without merging**
